language: node_js
node_js:
  - "10.15.3"
  - "12.0.0"
dist: trusty
sudo: required

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - npm run test-headless
  - ng build --prod --base-href https://ratherblue.github.io/resume-generator-angular/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/resume-generator-angular
  on:
    branch: master

notifications:
  on_success: false
  on_failure: change
